In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [ ]:
con = duckdb.connect("scripts\dados_duckdb.db")

In [39]:

arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-07-31 17:45:41.992024
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-07-31 17:45:41.992024
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-07-31 17:45:41.992024

In [40]:
con.execute("""
    create table if not exists bronze_produtos(
    NATBR VARCHAR,
    MAKTX VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST VARCHAR,
    nome_arquivo VARCHAR,
    data_ingestao TIMESTAMP

    )
""")

In [41]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [42]:
resultado = con.execute('SELECT * FROM bronze_produtos').fetchdf()
resultado.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-31 17:45:22.975874
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-31 17:45:22.975874
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-07-31 17:45:22.975874
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-07-31 17:45:41.992024
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-31 17:45:41.992024
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-07-31 17:45:41.992024

In [43]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [44]:
con.close()