In [2]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [38]:
con = duckdb.connect("scripts/dados_duckdb.db")

In [48]:

arquivo = "z0019_2.csv"
data_ingestao = datetime.now()
df = pd.read_csv(f"landing/{arquivo}",sep=";")
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10003    SERRA  BT50    100    200  z0019_2.csv 2026-07-31 16:58:43.002973
1  10003  MACHADO  BT50    100    100  z0019_2.csv 2026-07-31 16:58:43.002973
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-07-31 16:58:43.002973

In [49]:
con.execute("""
    create table if not exists bronze_produtos(
    NATBR VARCHAR,
    MAKTX VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST VARCHAR,
    nome_arquivo VARCHAR,
    data_ingestao TIMESTAMP

    )
""")

In [50]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [57]:
resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-31 16:57:00.888296
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-31 16:57:00.888296
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-07-31 16:57:00.888296
3  10003     SERRA  BT50   100   200  z0019_2.csv 2026-07-31 16:58:43.002973
4  10003   MACHADO  BT50   100   100  z0019_2.csv 2026-07-31 16:58:43.002973
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-07-31 16:58:43.002973

In [55]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [58]:
con.close()